on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
      - name: POST to endpoint
        run: |
          echo ${{ vars.ENDPOINT_URL }}
          curl -X POST ${{ vars.ENDPOINT_URL }} \
           -H "Content-Type: application/json" \
           -d '${{ vars.POST_DATA }}'
